require: rubocop-rspec

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/TrailingCommaInLiteral:
  Enabled: false

Metrics/LineLength:
  Max: 100

Documentation:
  Enabled: false
