language: ruby
script:
  - bundle exec rspec
  - bundle exec rubocop --display-cop-names
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
